# Generated by Django 4.2.21 on 2025-05-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('family', models.CharField(max_length=200, verbose_name='фамилия')),
                ('email', models.CharField(max_length=200, verbose_name='емаил')),
                ('img', models.FileField(default=None, upload_to='upl/', verbose_name='Фото')),
                ('status', models.CharField(max_length=200, verbose_name='статус')),
                ('password', models.CharField(max_length=200, verbose_name='пароль')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('editdate', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
    ]
